### PR TITLE
Allow JWT_AUDIENCES and sub JWT claim to be optional.

### PR DESCRIPTION
**Pull request by eventh**
The documentation in README claims that JWT_AUDIENCES are optional:

> JWT_AUDIENCES:
> Defines a list of accepted audiences (aud claim). If not provided, only tokens with no audience set will be accepted. The resource level audiences parameter is also available.

But with the current implementation one must provide both audiences and the "sub" JWT claim.

This pull request makes JWT_AUDIENCES/audiences optional, and removes the validation that "sub" is provided.

Also adds two tests that would fail on previous versions.

### CODE REVIEW

**Comment by rs** [comment]
Can you please fix the test so I can merge?

**Comment by eventh** [comment]
The tests aren't failing, it looks to me that installing dependencies on python3.3 is failing.

**Comment by rs** [comment]
I guess the requirement file needs a refresh. I can't fix it right now, if you can give it a try it would be super helpful.

**Comment by rs** [comment]
Please rebase on master so tests can pass.

**Comment by eventh** [comment]
Done

**Pull request merged**
